#index Routes :
se_platform_homepage:
    path:     /
    defaults:
        _controller: SEPlatformBundle:Default:index

# Filter Routes :
se_platform_departement_by_region:
    path: /annonces-en-cours/getDepartementByRegion
    defaults:
        _controller: SEPlatformBundle:Advert:getDepartementByRegion

se_platform_city_by_departement:
    path: /annonces-en-cours/getCityByDepartement
    defaults:
        _controller: SEPlatformBundle:Advert:getCityByDepartement

se_platform_postalCode_by_city_and_departement:
    path: /annonces-en-cours/getPostalCodeByCityAndDepartement
    defaults:
        _controller: SEPlatformBundle:Advert:getPostalCodeByCityAndDepartement

se_platform_postalCode:
    path: /getpostalcode
    defaults:
        _controller: SEPlatformBundle:PostalCode:getPostalCode

# Advert Routes :
se_platform_advert_add:
    path:   /profil/annonce/ajouter
    defaults:
        _controller: SEPlatformBundle:Advert:add

se_platform_advert_view:
    path:   /annonce/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:view
    requirements:
        id: \d+

se_platform_advert_edit:
    path:   /profil/annonce/modifier/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:edit
    requirements:
        id: \d+

se_platform_advert_delete:
    path:   /profil/annonce/supprimer/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:delete
    requirements:
        id: \d+

se_platform_advert_list:
    path:   /annonces-en-cours/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:list
        page:   1
    requirements:
        page: \d*

se_platform_advert_user_list:
    path:   /profil/mes-annonces/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:listUser
        page:   1
    requirements:
        page: \d*

# Auction Routes :
se_platform_auction_user_receive:
    path:   /profil/encheres-recues/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userReceiveList
        page:   1
    requirements:
        page: \d*

se_platform_auction_user_send:
    path:   /profil/encheres-proposees/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userSendList
        page:   1
    requirements:
        page: \d*

# Message Routes :
se_platform_message_add:
    path:   /profil/envoyer-message
    defaults:
        _controller: SEPlatformBundle:Message:add

se_platform_message_view:
    path:   /profil/consulter-message
    defaults:
        _controller: SEPlatformBundle:Message:view

se_platform_message_edit:
    path:   /profil/modifier-message
    defaults:
        _controller: SEPlatformBundle:Message:edit

se_platform_message_delete:
    path:   /profil/supprimer-message
    defaults:
        _controller: SEPlatformBundle:Message:supprimer

se_platform_message_user_list:
    path:   /profil/mes-messages/{page}
    defaults:
        _controller: SEPlatformBundle:Message:listUser
        page:   1
    requirements:
        page: \d*

# Comment Routes :
se_platform_comment_add:
    path:   /profil/ajouter-avis
    defaults:
        _controller: SEPlatformBundle:Comment:add

se_platform_comment_view:
    path:   /profil/consulter-avis
    defaults:
        _controller: SEPlatformBundle:Comment:view

se_platform_comment_edit:
    path:   /profil/modifier-avis
    defaults:
        _controller: SEPlatformBundle:Comment:edit

se_platform_comment_delete:
    path:   /profil/supprimer-avis
    defaults:
        _controller: SEPlatformBundle:Comment:supprimer

se_platform_comment_user_list:
    path:   /profil/mes-avis/{page}
    defaults:
        _controller: SEPlatformBundle:Comment:listUser
        page:   1
    requirements:
        page: \d*

#Account Routes :
se_platform_user_add:
    path:   /creer-compte
    defaults:
        _controller: SEPlatformBundle:User:add

se_platform_user_view:
    path:   /profile
    defaults:
        _controller: SEPlatformBundle:User:view

se_platform_user_edit:
    path:   /profil/edit
    defaults:
        _controller: SEPlatformBundle:User:edit

se_platform_user_delete:
    path:   /profil/mon-compte/supprimer
    defaults:
        _controller: SEPlatformBundle:User:supprimer

se_platform_user_login:
    path:   /se-connecter
    defaults:
        _controller: SEPlatformBundle:User:login

se_platform_user_logout:
    path:   /profil/se-déconnecter
    defaults:
        _controller: SEPlatformBundle:User:logout

#Default Pages
se_platform_resum:
    path: /qui-sommes-nous
    defaults:
        _controller: SEPlatformBundle:Default:resum

se_platform_cgu:
    path:     /conditions-generales-d-utilisations
    defaults:
        _controller: SEPlatformBundle:Default:cgu

se_platform_help:
    path: /aide
    defaults:
        _controller: SEPlatformBundle:Default:help
