# index Routes :
se_platform_homepage:
    path:     /
    defaults:
        _controller: SEPlatformBundle:Default:index

# Advert Routes :
se_platform_advert_add:
    path:   /annonce/ajouter
    defaults:
        _controller: SEPlatformBundle:Advert:add

se_platform_advert_view:
    path:   /annonce/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:view
    requirements:
        id: \d+

se_platform_advert_edit:
    path:   /annonce/modifier/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:edit
    requirements:
        id: \d+

se_platform_advert_delete:
    path:   /annonce/supprimer/{slug}/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:delete
    requirements:
        id: \d+

se_platform_advert_list:
    path:   /annonces-en-cours/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:list
        page:   1
    requirements:
        page: \d*

se_platform_advert_user_list:
    path:   /mes-annonces/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:userList
        page:   1
    requirements:
        page: \d*

# Auction Routes :
se_platform_auction_user_receive:
    path:   /encheres-recues/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userReceiveList
        page:   1
    requirements:
        page: \d*

se_platform_auction_user_send:
    path:   /encheres-proposees/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userSendList
        page:   1
    requirements:
        page: \d*

# Message Routes :
se_platform_message_user_list:
    path:   /mes-messages/{page}
    defaults:
        _controller: SEPlatformBundle:Message:userList
        page:   1
    requirements:
        page: \d*

#Account Routes :
se_platform_user_add:
    path:   /creer-compte
    defaults:
        _controller: SEPlatformBundle:User:add

se_platform_user_view:
    path:   /mon-compte
    defaults:
        _controller: SEPlatformBundle:User:view

se_platform_user_edit:
    path:   /modifier-mon-compte
    defaults:
        _controller: SEPlatformBundle:User:edit

se_platform_user_delete:
    path:   /supprimer-mon-compte
    defaults:
        _controller: SEPlatformBundle:User:supprimer

se_platform_user_login:
    path:   /se-connecter
    defaults:
        _controller: SEPlatformBundle:User:login

se_platform_user_logout:
    path:   /se-déconnecter
    defaults:
        _controller: SEPlatformBundle:User:logout

#Default Pages
se_platform_resum:
    path: /qui-sommes-nous
    defaults:
        _controller: SEPlatformBundle:Default:resum

se_platform_cgu:
    path:     /conditions-generales-d-utilisations
    defaults:
        _controller: SEPlatformBundle:Default:cgu

se_platform_help:
    path: /aide
    defaults:
        _controller: SEPlatformBundle:Default:help
