#index Routes :
se_platform_homepage:
    path:     /
    defaults:
        _controller: SEPlatformBundle:Default:index

# Admin Routes :
se_platform_admin_list_users:
    path:     /manage/users/{page}
    defaults:
        _controller: SEPlatformBundle:Admin:listUsers
        page:   1
    requirements:
        page: \d*

se_platform_admin_view_user:
    path:   /manage/user-{id}
    defaults:
        _controller: SEPlatformBundle:Admin:viewUser
    requirements:
        id: \d+


se_platform_admin_enabled_user:
    path:   /manage/activer/user-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:enableUser
    requirements:
        id: \d+

se_platform_admin_newsletter_user:
    path:   /manage/newsletter/user-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:newsletterUser
    requirements:
        id: \d+

se_platform_admin_visible_user:
    path:   /manage/visible/user-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:visibleUser
    requirements:
        id: \d+

se_platform_admin_view_advert:
    path:   /manage/demande-{id}
    defaults:
        _controller: SEPlatformBundle:Admin:viewAdvert
    requirements:
        id: \d+

se_platform_admin_enabled_advert:
    path:   /manage/activer/demande-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:enableAdvert
    requirements:
        id: \d+

se_platform_admin_publish_advert:
    path:   /manage/publier/demande-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:publishAdvert
    requirements:
        id: \d+

se_platform_admin_delete_advert:
    path:   /manage/supprimer/demande-{id}-{action}
    defaults:
        _controller: SEPlatformBundle:Admin:deleteAdvert
    requirements:
        id: \d+

se_platform_admin_list_adverts:
    path:     /manage/adverts/{page}
    defaults:
        _controller: SEPlatformBundle:Admin:listAdverts
        page:   1
    requirements:
        page: \d*

se_platform_admin_list_auctions:
    path:     /manage/auctions
    defaults:
        _controller: SEPlatformBundle:Admin:listAuctions
        page:   1
    requirements:
        page: \d*

se_platform_admin_list_messages:
    path:     /manage/messages
    defaults:
        _controller: SEPlatformBundle:Admin:listMessages
        page:   1
    requirements:
        page: \d*

se_platform_admin_list_comments:
    path:     /manage/comments
    defaults:
        _controller: SEPlatformBundle:Admin:listComments
        page:   1
    requirements:
        page: \d*

# Filter Routes :
se_platform_departement_by_region:
    path: /demandes-en-cours/getDepartementByRegion
    defaults:
        _controller: SEPlatformBundle:Advert:getDepartementByRegion

se_platform_city_by_departement:
    path: /demandes-en-cours/getCityByDepartement
    defaults:
        _controller: SEPlatformBundle:Advert:getCityByDepartement

se_platform_postalCode_by_city_and_departement:
    path: /demandes-en-cours/getPostalCodeByCityAndDepartement
    defaults:
        _controller: SEPlatformBundle:Advert:getPostalCodeByCityAndDepartement

se_platform_postalCode:
    path: /getpostalcode
    defaults:
        _controller: SEPlatformBundle:Default:getPostalCode

# Advert Routes :
se_platform_advert_add:
    path:   /demande-service/ajouter
    defaults:
        _controller: SEPlatformBundle:Advert:add

se_platform_advert_view:
    path:   /demande/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:view
    requirements:
        id: \d+

se_platform_advert_view_user:
    path:   /ma-demande/{id}
    defaults:
        _controller: SEPlatformBundle:Advert:viewUser
    requirements:
        id: \d+

se_platform_advert_validate:
    path:   /demande/validee/{action}
    defaults:
        _controller: SEPlatformBundle:Advert:validate

se_platform_advert_edit:
    path:   /demande/modifier/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:edit
    requirements:
        id: \d+

se_platform_advert_delete:
    path:   /demande/supprimer/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:delete
    requirements:
        id: \d+

se_platform_advert_disable:
    path:   /demande/desactiver/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:disable
    requirements:
        id: \d+

se_platform_auction_cancel:
    path:   /offre/annuler/{id}
    defaults:
        _controller: SEPlatformBundle:Auction:cancel
    requirements:
        id: \d+

se_platform_advert_unpublish:
    path:   /demande/desactiver/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:unpublish
    requirements:
        id: \d+

se_platform_advert_publish:
    path:   /demande/activer/{slug}_{id}
    defaults:
        _controller: SEPlatformBundle:Advert:publish
    requirements:
        id: \d+

se_platform_advert_list:
    path:   /demandes-en-cours/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:list
        page:   1
    requirements:
        page: \d*

se_platform_advert_user_list:
    path:   /mes-demandes/{page}
    defaults:
        _controller: SEPlatformBundle:Advert:listUser
        page:   1
    requirements:
        page: \d*

# Auction Routes :
se_platform_auction_list:
    path:   /offre-en-cours/{advertId}
    defaults:
        _controller: SEPlatformBundle:Auction:list
    requirements:
        advertId: \d+

se_platform_auction_user_receive:
    path:   /offres-recues/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userReceiveList
        page:   1
    requirements:
        page: \d*

se_platform_auction_user_send:
    path:   /offres-proposees/{page}
    defaults:
        _controller: SEPlatformBundle:Auction:userSendList
        page:   1
    requirements:
        page: \d*

se_platform_auction_add:
    path:     /offre/propser-offre/{advertSlug}_{advertId}
    defaults:
        _controller: SEPlatformBundle:Auction:add
    requirements:
        advertId: \d+

se_platform_auction_accept:
    path:     /offre/accepter-offre/{auctionId}
    defaults:
        _controller: SEPlatformBundle:Auction:accept

se_platform_auction_refuse:
    path:     /offre/refuser-offre/{auctionId}
    defaults:
        _controller: SEPlatformBundle:Auction:refuse

# Message Routes :
se_platform_message_add:
    path:   /envoyer-message/{advertSlug}_{advertId}_{receiveId}_{isAnswer}_{msgId}
    defaults:
        _controller: SEPlatformBundle:Message:add
    requirements:
        advertId: \d+
        receiveId: \d+

se_platform_message_answer:
    path:   /envoyer-reponse/{advertSlug}_{advertId}_{receiveId}_{isAnswer}_{msgId}
    defaults:
        _controller: SEPlatformBundle:Message:add
    requirements:
        advertId: \d+
        receiveId: \d+

se_platform_message_view:
    path:   /consulter-message/{advertSlug}_{advertId}
    defaults:
        _controller: SEPlatformBundle:Message:view
    requirements:
        advertId: \d+

se_platform_message_edit:
    path:   /modifier-message/{id}
    defaults:
        _controller: SEPlatformBundle:Message:edit
    requirements:
        id: \d+

se_platform_message_delete:
    path:   /supprimer-message/{id}
    defaults:
        _controller: SEPlatformBundle:Message:supprimer
    requirements:
        id: \d+

se_platform_message_user_list:
    path:   /mes-messages/{page}
    defaults:
        _controller: SEPlatformBundle:Message:listUser
        page:   1
    requirements:
        page: \d*

se_platform_message_user_receive:
    path:   /mes-messages-recues/{page}
    defaults:
        _controller: SEPlatformBundle:Message:userReceiveList
        page:   1
    requirements:
        page: \d*

se_platform_message_user_send:
    path:   /mes-messages-envoyes/{page}
    defaults:
        _controller: SEPlatformBundle:Message:userSendList
        page:   1
    requirements:
        page: \d*

se_platform_message_advert_send:
    path:     /message-envoyes/{advertId}_{receiverId}
    defaults:
        _controller: SEPlatformBundle:Message:listSendConversation

se_platform_message_advert_receive:
    path:     /message-recues/{advertId}_{senderId}
    defaults:
        _controller: SEPlatformBundle:Message:listReceiveConversation

# Comment Routes :
se_platform_comment_add:
    path:   /ajouter-avis/{advertId}_{auctionUserId}
    defaults:
        _controller: SEPlatformBundle:Comment:add

se_platform_comment_view:
    path:   /consulter-avis/
    defaults:
        _controller: SEPlatformBundle:Comment:view

se_platform_comment_edit:
    path:   /modifier-avis/{id}
    defaults:
        _controller: SEPlatformBundle:Comment:edit
    requirements:
        id: \d+

se_platform_comment_delete:
    path:   /supprimer-avis/{id}
    defaults:
        _controller: SEPlatformBundle:Comment:delete
    requirements:
        id: \d+

se_platform_comment_user_list:
    path:   /mes-avis/{page}
    defaults:
        _controller: SEPlatformBundle:Comment:listUser
        page:   1
    requirements:
        page: \d*

#Account Routes :
se_platform_user_add:
    path:   /creer-compte
    defaults:
        _controller: SEPlatformBundle:User:add

se_platform_user_view:
    path:   /profile-{userId}
    defaults:
        _controller: SEPlatformBundle:Profile:view
    requirements:
        userId: \d+

se_platform_user_edit:
    path:   /mon-compte/modifier
    defaults:
        _controller: SEPlatformBundle:User:edit

se_platform_user_delete:
    path:   /mon-compte/supprimer
    defaults:
        _controller: SEPlatformBundle:User:supprimer

se_platform_user_login:
    path:   /se-connecter
    defaults:
        _controller: SEPlatformBundle:User:login

se_platform_user_logout:
    path:   /se-deconnecter
    defaults:
        _controller: SEPlatformBundle:User:logout

se_platform_user_jobbeur_list:
    path:   /liste-des-jobbers/{page}
    defaults:
          _controller: SEPlatformBundle:User:jobbeurList
          page:   1
    requirements:
        page: \d*

#Default Pages
se_platform_blog:
    path: /blog
    defaults:
        _controller: SEPlatformBundle:Default:blog

se_platform_resum:
    path: /qui-sommes-nous
    defaults:
        _controller: SEPlatformBundle:Default:resum

se_platform_cgu:
    path:     /conditions-generales-d-utilisations
    defaults:
        _controller: SEPlatformBundle:Default:cgu

se_platform_help:
    path: /aide
    defaults:
        _controller: SEPlatformBundle:Default:help
