<?php

namespace SE\AuctionBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Tools\Pagination\Paginator;

class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.category', 'c')
            ->addSelect('c')
            ->orderBy('a.dateCreation', 'DESC');

        $qb->where($qb->expr()->eq('a.isPublished', 1))
                ->andWhere($qb->expr()->eq('a.isDeleted', 0))
                ->andWhere($qb->expr()->eq('a.isEnabled', 1));

        $qb
            ->getQuery()
            // On définit l'annonce à partir de laquelle commencer la liste
            ->setFirstResult(($page-1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage);

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($qb, true);
    }
    public function getAdvertWithCategory($catgeory, $limit)
    {
        $qb=$this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.category', 'c')
            ->addSelect('c');

        $qb->where($qb->expr()->eq('c.slug', "'".$catgeory."'"))
        ->andWhere($qb->expr()->eq('a.isPublished', 1))
        ->andWhere($qb->expr()->eq('a.isDeleted', 0))
        ->andWhere($qb->expr()->eq('a.isEnabled', 1));
        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();
    }
    
    public function getAdvertByRegion($region, $limit){
        $qb=$this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.city', 'c')
            ->addSelect('c')
            ->leftJoin('c.departement', 'd')
            ->addSelect('d')
            ->leftJoin('d.region', 'r')
            ->addSelect('r')
                
            ->orderBy('a.dateCreation', 'DESC');

        $qb->where($qb->expr()->eq('r.slug', "'".$region."'"))
        ->andWhere($qb->expr()->eq('a.isPublished', 1))
        ->andWhere($qb->expr()->eq('a.isDeleted', 0))
        ->andWhere($qb->expr()->eq('a.isEnabled', 1));

        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAdvertByUser($userId, $limit){
        
     $qb=$this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.user', 'u')
            ->addSelect('u');

        $qb->where($qb->expr()->eq('u.id', $userId));

        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();   
    }

    public function getCountAdvertByCategory($catgeoryId)
    {
        $qb=$this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.category', 'c')
            ->addSelect('c');

        $qb->where($qb->expr()->eq('c.id', $catgeoryId))        
                ->andWhere($qb->expr()->eq('a.isPublished', 1))
                ->andWhere($qb->expr()->eq('a.isDeleted', 0))
                ->andWhere($qb->expr()->eq('a.isEnabled', 1));

        return $qb
            ->getQuery()
            ->getScalarResult();
    }

}
