<?php

namespace SE\PortalBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrder()
    {
        return $this->findBy(array(), array('position' => 'ASC'));
    }
}
