# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.profile:
        class: SE\PlatformBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: se_platform_user_profile }
    se_platform.mailer:
        class: SE\PlatformBundle\Service\Mailer
        arguments :
            - "@mailer"
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
