<?php

namespace SE\PlatformBundle\Repository;

/**
 * AdvertStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertStateRepository extends \Doctrine\ORM\EntityRepository
{
}
