<?php

namespace SE\PlatformBundle\Repository;

/**
 * AuctionStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionStateRepository extends \Doctrine\ORM\EntityRepository
{
}
