<?php

namespace SE\PlatformBundle\Repository;

/**
 * BudgetTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
