<?php

namespace SE\PlatformBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
   public function getCityByDepartement($departement){

       $qb=$this->createQueryBuilder('city');

        $qb
            ->innerJoin('city.departement', 'departement')
            ->addSelect('departement');

        if($departement !== NULL && $departement !== '0')
        {
            $qb->where($qb->expr()->eq('departement.id', $departement));
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
