<?php

namespace SE\PlatformBundle\Repository;

/**
 * CommentStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentStateRepository extends \Doctrine\ORM\EntityRepository
{
}
