<?php

namespace SE\PlatformBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDptByRegion($region)
    {
        $qb=$this->createQueryBuilder('departement');

        $qb
           ->innerJoin('departement.region', 'region')
            ->addSelect('region');

        if($region !== NULL && $region !== '0')
        {
              $qb->where($qb->expr()->eq('region.id', $region));
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
