<?php

namespace SE\PlatformBundle\Repository;

/**
 * MessageStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageStateRepository extends \Doctrine\ORM\EntityRepository
{
}
