<?php

namespace SE\PlatformBundle\Repository;

/**
 * PotentialUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

 use Doctrine\ORM\Tools\Pagination\Paginator;

class PotentialUserRepository extends \Doctrine\ORM\EntityRepository
{


  public function getUserPotentialListAdmin($page, $nbPerPage){
      $qb = $this->createQueryBuilder('PotentialUser');

      $qb->orderBy('PotentialUser.dateSendMail', 'DESC')->getQuery();
      $qb->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);

      return new Paginator($qb, true);
  }
}
