<?php

namespace SE\PlatformBundle\Repository;


/**
 * SocietyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocietyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
