#Portal - Account
se_portal_account_dashboard:
    path:     /tableau-de-bord
    defaults:
        _controller: SEPortalBundle:Account:dashboard

se_portal_account_profile:
    path:     /mon-profile
    defaults:
        _controller: FOSUserBundle:Profile:show

se_portal_account_profile_edit:
    path:     /modifier-mon-profile
    defaults:
        _controller: FOSUserBundle:Profile:edit

